name: PR

on:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18, 20]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: setup bun
        uses: oven-sh/setup-bun@v2

      - name: install dependencies
        run: bun install --frozen-lockfile

      - name: test
        run: bun run test && bun run build

  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: initialize codeql
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: perform codeql analysis
        uses: github/codeql-action/analyze@v3
